# serverless.yml

service: log-everymundo-microservice

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-offline
  - serverless-apigw-binary

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: false
  apigwBinary:
    types:
      - 'text/plain'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  environment:
    SECRET_KEY: XXXXXXXXX
    BUCKET_NAME: XXXXXX
    ACCESS_KEY: XXXXX
    SECRET: XXXXXXXX

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'