# serverless.yml

service: manage-logs-everymundo-microservice

plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-offline
  - serverless-apigw-binary

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: false
  apigwBinary:
    types:
      - 'text/plain'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  environment:
    SECRET_KEY: /THgYhQJ1O6GrTJS8CYWMpdMEQGHfBqD3AHgwMng
    BUCKET_NAME: logs-everymundo-bucket
    BUCKET_NAME_SUSCRIPTORS: subscriptors-everymundo-bucket
    ACCESS_KEY: AKIAZIKQ6V2GZFXZOHNH

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'